# Generated by Django 4.1.7 on 2023-02-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_ingredient_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MockRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_recipe_name', models.CharField(max_length=50)),
                ('m_cooking_instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MockRecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CartBuilder.mockingredient')),
                ('m_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CartBuilder.mockrecipe')),
            ],
        ),
        migrations.AddField(
            model_name='mockrecipe',
            name='m_ingredients',
            field=models.ManyToManyField(through='CartBuilder.MockRecipeIngredient', to='CartBuilder.mockingredient'),
        ),
    ]
