# Generated by Django 4.1.7 on 2023-03-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergicIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='allergic_ingredients',
            field=models.ManyToManyField(to='CartBuilder.allergicingredient'),
        ),
    ]
