# Generated by Django 4.1.7 on 2023-02-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0002_mockingredient_mockrecipe_mockrecipeingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockrecipe',
            name='m_cooking_instructions',
            field=models.CharField(max_length=500),
        ),
    ]
