# Generated by Django 4.1.7 on 2023-03-02 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0002_allergicingredient_recipe_allergic_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTenMockAllergicIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('allergic_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CartBuilder.ingredient')),
            ],
        ),
    ]
