# Generated by Django 4.1.7 on 2023-03-02 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0003_toptenmockallergicingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toptenmockallergicingredients',
            name='allergic_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CartBuilder.mockallergicingredient'),
        ),
    ]
