# Generated by Django 4.1.7 on 2023-02-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0003_alter_mockrecipe_m_cooking_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockrecipe',
            name='m_cooking_instructions',
            field=models.TextField(max_length=500),
        ),
    ]
