# Generated by Django 4.1.7 on 2023-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0004_alter_mockrecipe_m_cooking_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockCookingInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_cooking_instruction', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mockrecipe',
            name='m_cooking_instructions',
        ),
        migrations.AddField(
            model_name='mockrecipe',
            name='m_cooking_instructions',
            field=models.ManyToManyField(to='CartBuilder.mockcookinginstruction'),
        ),
    ]
