# Generated by Django 4.1.7 on 2023-03-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0004_alter_toptenmockallergicingredients_allergic_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='toptenmockallergicingredients',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
