# Generated by Django 4.1.7 on 2023-03-03 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0005_toptenmockallergicingredients_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorites',
        ),
    ]
