# Generated by Django 4.1.7 on 2023-02-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0006_remove_ingredient_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_instructions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_instructions',
            field=models.ManyToManyField(to='CartBuilder.cookinginstruction'),
        ),
    ]
