# Generated by Django 4.1.7 on 2023-02-21 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0007_cookinginstruction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_instructions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='_cooking_instruction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CartBuilder.cookinginstruction'),
            preserve_default=False,
        ),
    ]
