# Generated by Django 4.1.7 on 2023-03-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0007_recipe_favorite_recipes_alter_recipefavorite_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorite_recipes',
            field=models.ManyToManyField(related_name='recipes_favorited', through='CartBuilder.RecipeFavorite', to='CartBuilder.profile'),
        ),
    ]
