# Generated by Django 4.1.7 on 2023-02-21 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0008_remove_recipe_cooking_instructions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='_cooking_instruction',
            new_name='cooking_instruction',
        ),
    ]
