# Generated by Django 4.1.7 on 2023-03-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0008_alter_recipe_favorite_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipefavorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_with_favorite_recipe', to='CartBuilder.recipe'),
        ),
        migrations.CreateModel(
            name='RecipePersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_recipe_relations', to='CartBuilder.profile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_with_personal_recipe', to='CartBuilder.recipe')),
            ],
        ),
    ]
