# Generated by Django 4.1.7 on 2023-02-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0009_rename__cooking_instruction_recipe_cooking_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_instruction',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CookingInstruction',
        ),
    ]
