# Generated by Django 4.1.7 on 2023-03-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0011_rename_profile_id_recipe_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toptenmockallergicingredients',
            name='allergic_ingredient',
            field=models.CharField(max_length=50),
        ),
    ]
