# Generated by Django 4.1.7 on 2023-03-22 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0012_alter_toptenmockallergicingredients_allergic_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleIngredient',
            fields=[
                ('Ingredients_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Ingredients_Name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleRecipe',
            fields=[
                ('recipeKey', models.IntegerField(primary_key=True, serialize=False)),
                ('recipeName', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleRecipeIngredientBlurb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField()),
                ('recipeKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CartBuilder.simplerecipe')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleRecipeDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directions', models.TextField()),
                ('recipeKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CartBuilder.simplerecipe')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleNERIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NER_Name', models.CharField(max_length=60)),
                ('recipeKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CartBuilder.simplerecipe')),
            ],
        ),
    ]
