# Generated by Django 4.1.7 on 2023-03-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0012_alter_toptenmockallergicingredients_allergic_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_instruction', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='mockrecipe',
            name='m_instructions',
            field=models.ManyToManyField(to='CartBuilder.mockinstruction'),
        ),
    ]
