# Generated by Django 4.1.7 on 2023-03-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0013_mockinstruction_mockrecipe_m_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.ManyToManyField(to='CartBuilder.instruction'),
        ),
    ]
