# Generated by Django 4.1.7 on 2023-03-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0013_simpleingredient_simplerecipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleneringredient',
            name='recipeKey',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='simplerecipedirection',
            name='recipeKey',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='simplerecipeingredientblurb',
            name='recipeKey',
            field=models.IntegerField(),
        ),
    ]
