# Generated by Django 4.1.7 on 2023-04-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0014_alter_simpleneringredient_recipekey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeKey', models.IntegerField()),
                ('recipeTitle', models.TextField()),
                ('recipeIngredients', models.TextField()),
                ('recipeDirections', models.TextField()),
                ('recipeNER', models.TextField()),
            ],
        ),
    ]
