# Generated by Django 4.1.7 on 2023-03-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0014_alter_simpleneringredient_recipekey_and_more'),
        ('CartBuilder', '0014_instruction_recipe_instructions'),
    ]

    operations = [
    ]
