# Generated by Django 4.1.7 on 2023-04-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0015_merge_20230323_0834'),
        ('CartBuilder', '0015_simplemaster'),
    ]

    operations = [
    ]
