# Generated by Django 4.1.7 on 2023-04-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartBuilder', '0016_merge_0015_merge_20230323_0834_0015_simplemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplemaster',
            name='recipeImage',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
